[package]
name = "ucd_generate_alphabets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ucd_parser = { path = "../ucd_parser", version = "0.1.0" }
